version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/mydb

      - image: postgres:9.6.2-alpine
          environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: mydb

          steps:
            - checkout
            - run: sudo apt-get update
            - run: sudo apt-get install -y postgresql-client-9.6
            - run:
                name: install dockerize
                command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
                environment:
                  DOCKERIZE_VERSION: v0.3.0

            - restore_cache:
                key: circleci-challenge-{{ checksum "pom.xml" }}

            - run: mvn dependency:go-offline

            - save_cache:
                paths:
                  - ~/.m2
                key: circleci-challenge-{{ checksum "pom.xml" }}

            - run:
                name: Wait for db
                command: dockerize -wait tcp://localhost:5432 -timeout 1m

            steps:
              - run: whoami
              - run: |
                  psql \
                  -d $TEST_DATABASE_URL \
                  -c "CREATE TABLE test (name char(25));"
              - run: |
                  psql \
                  -d $TEST_DATABASE_URL \
                  -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
              - run: |
                  psql \
                  -d $TEST_DATABASE_URL \
                  -c "SELECT * from test"
            #- run:
            #    name: Create DB
            #    command: sh utils/sizebay-circleci/circle.db.setup utils/sizebay-db/${TEST_DATABASE}.sql

            #- run: mysql -h 127.0.0.1 -u root -proot -e "show databases"
            #- run: mysql -h 127.0.0.1 -u root -proot -e "SELECT User, Host FROM mysql.user;"
            #- run: mvn -s utils/sizebay-circleci/circle.maven-settings.xml -Dconfig.skip.tests=true clean package
            #- run: mvn -s utils/sizebay-circleci/circle.maven-settings.xml clean test

  #deploy-prod:
  #  machine: true
  #  working_directory: ~/project
  #  steps:
  #    - checkout
  #    - run: git clone git@github.com:sizebay/Severino.git utils
  #    - run:
  #        name: Deploy app in aws usaing maven
  #        command:  mvn -s utils/sizebay-circleci/circle.maven-settings.xml -Dconfig.skip.tests=true clean deploy -Pdeploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      #- deploy-prod:
      #   filters:
      #      branches:
      #       only: master