version: 2
jobs:
  build:

    # Primary container image where all commands run

    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test

      # Service container image

      - image: circleci/postgres:9.6.5-alpine-ram

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt install postgresql-client
      - run: whoami
      - restore_cache:
          key: circleci-challenge-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-challenge-{{ checksum "pom.xml" }}

      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE person

              (
                id character varying NOT null,
                name character varying(50),
                last_name character varying(50),
                age integer NOT NULL,
                CONSTRAINT person_pkey PRIMARY KEY (id),
                CONSTRAINT person_name_key UNIQUE (name)
              );"

      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "INSERT INTO person VALUES ('123456', 'Elon', 'Musk', 35);"

      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "SELECT * from person"
          
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          filters:
            branches:
              only: master